powerball2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from powb import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index),
    url(r'^add_player$', views.add_player),
    url(r'^clean_data$', views.clean_data),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

powb/models.py
from __future__ import unicode_literals

from django.db import models


class Player(models.Model):
    """ A virtual person playing lottery numbers """
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    n1 = models.IntegerField(default=1)
    n2 = models.IntegerField(default=1)
    n3 = models.IntegerField(default=1)
    n4 = models.IntegerField(default=1)
    n5 = models.IntegerField(default=1)
    powb = models.IntegerField(default=1)

    def __str__(self):
        return "{0} {1}".format(self.firstname, self.lastname)

    class Meta:
        verbose_name = "Player"
        verbose_name_plural = "Players"
        ordering = ('firstname', 'lastname')

    def representation(self):
        return "\n{0} {1} {2} {3} {4} {5} {6} PowerBall: {7}".format(self.firstname,
                                                                     self.lastname,
                                                                     self.n1, self.n2, self.n3, self.n4, self.n5,
                                                                     self.powb)

powb/forms.py
from __future__ import unicode_literals

from django import forms


class PlayersForm(forms.Form):
    firstname = forms.CharField(label='FirstName', max_length=100,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(label='LastName', max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    n1 = forms.IntegerField(initial=1, label='N1',
                            widget=forms.TextInput(attrs={'class': 'form-control input-20 atright'}))
    n2 = forms.IntegerField(initial=1, label='N2',
                            widget=forms.TextInput(attrs={'class': 'form-control input-20 atright'}))
    n3 = forms.IntegerField(initial=1, label='N3',
                            widget=forms.TextInput(attrs={'class': 'form-control input-20 atright'}))
    n4 = forms.IntegerField(initial=1, label='N4',
                            widget=forms.TextInput(attrs={'class': 'form-control input-20 atright'}))
    n5 = forms.IntegerField(initial=1, label='N5',
                            widget=forms.TextInput(attrs={'class': 'form-control input-20 atright'}))
    powb = forms.IntegerField(initial=1, label='PwB',
                              widget=forms.TextInput(attrs={'class': 'form-control input-20 atright'}))

powb/views.py
from __future__ import unicode_literals

from collections import defaultdict

import operator
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render

from powb.forms import PlayersForm
from powb.functions import bad_json, ok_json
from powb.models import Player


def generate_winning_numbers(players):
    general_numbers_list = []
    general_powerball_ist = []
    if players:
        for elem in players:
            general_numbers_list.append(elem.n1)
            general_numbers_list.append(elem.n2)
            general_numbers_list.append(elem.n3)
            general_numbers_list.append(elem.n4)
            general_numbers_list.append(elem.n5)
            general_powerball_ist.append(elem.powb)

        appearances = defaultdict(int)
        appearances_powb = defaultdict(int)
        for curr in general_numbers_list:
            appearances[curr] += 1
        favorites_numbers = dict(sorted(appearances.iteritems(), key=operator.itemgetter(1), reverse=True)[:5])
        for curr in general_powerball_ist:
            appearances_powb[curr] += 1
        favorite_powerball = dict(sorted(appearances_powb.iteritems(), key=operator.itemgetter(1), reverse=True)[:1])
        return ",".join(str(n) for n in favorites_numbers.keys()) + ',{}'.format(favorite_powerball.keys().pop())
    return ""


def index(request):
    players = Player.objects.all()
    list = generate_winning_numbers(players)
    if list:
        favorite_numbers = sorted(list.split(',')[:5])
        powerball_number = list.split(',')[-1:][0]
    else:
        favorite_numbers = ['', '', '', '', '']
        powerball_number = ['']
    return render(request, 'index.html',
                  {
                      'title': 'Python Code Sample Project',
                      'players': players,
                      'favorite_numbers': favorite_numbers,
                      'powerball_number': powerball_number
                  })


def add_player(request):
    if request.method == 'POST':
        f = PlayersForm(request.POST)
        temp = []
        if f.is_valid():
            try:
                with transaction.atomic():
                    n1 = f.cleaned_data['n1']
                    n2 = f.cleaned_data['n2']
                    n3 = f.cleaned_data['n3']
                    n4 = f.cleaned_data['n4']
                    n5 = f.cleaned_data['n5']
                    temp.append(n1)
                    temp.append(n2)
                    temp.append(n3)
                    temp.append(n4)
                    temp.append(n5)
                    if len(temp) != len(set(temp)):
                        return bad_json(mensaje='ALERT: DUPLICATE NUMBERS ON YOUR LIST')
                    player = Player(firstname=f.cleaned_data['firstname'],
                                    lastname=f.cleaned_data['lastname'],
                                    n1=n1, n2=n2, n3=n3, n4=n4, n5=n5,
                                    powb=f.cleaned_data['powb'])
                    player.save()
                    return ok_json()
            except:
                return bad_json(error=1)
        else:
            return bad_json(error=1)

    return render(request, 'players/add.html',
                  {
                      'title': 'Add Player',
                      'form': PlayersForm()
                  })


def clean_data(request):
    Player.objects.all().delete()
    return HttpResponseRedirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Powerball Sample Project">
    <meta name="author" content="George Navarro">

    <title>{{ title }}</title>

    <link href="/static/img/favicon.ico" rel="shortcut icon"/>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/static/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/static/css/mystyles.css" rel="stylesheet"/>
    <link href="/static/css/validationEngine.jquery.css" rel="stylesheet"/>
    <link href="/static/css/smoke.css" rel="stylesheet"/>

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.validationEngine.js"></script>
    <script src="/static/js/jquery.validationEngine-es.js"></script>
    <script src="/static/js/jquery.blockUI.js"></script>
    <script src="/static/js/smoke.min.js"></script>

    <script>

        $(function () {

            numerico = function(elemento, min, max, decimales) {
                var nvalor;
                var valor = elemento.val();
                if (valor==""){
                    valor = parseFloat(min).toFixed(decimales);
                    elemento.val(valor);
                    return;
                }
                if (isNaN(valor)){
                    nvalor = parseFloat(min).toFixed(decimales);
                    elemento.val(nvalor);
                    return;
                }
                if (valor < min) {
                    nvalor = parseFloat(min).toFixed(decimales);
                    elemento.val(nvalor);
                    return;
                }
                if (max>0 && valor>max){
                    nvalor = parseFloat(max).toFixed(decimales);
                    elemento.val(nvalor);
                    return;
                }
                nvalor = parseFloat(valor).toFixed(decimales);
                elemento.val(nvalor);
            };

            bloqueointerface = function(){
                $.blockUI({message: null });
            };

            $(".btn-form").click(function(){
                bloqueointerface();
            });

            $(".tt").tooltip({placement:"top"});
            $(".tb").tooltip({placement:"bottom"});
            $(".tr").tooltip({placement:"right"});
            $(".tl").tooltip({placement:"left"});

        });

    </script>
    {% block heading %}
    {% endblock %}

</head>

<body>

<div id="wrap">
    {% block navbar %}
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><img src="/static/img/logo.png" style="height: 25px"/></a>
                </div>
            </div>
        </div>
    {% endblock %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>

<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-md-10 text-center">
                <p class="text-muted credit">
                    Powerball Sample Project
                </p>
            </div>
            <div class="col-lg-2 col-md-2 text-right">
                <p class="text-muted credit">
                    <a href="http://twitter.com/aokgeorge" target="_blank"><i class="fa fa-twitter-square"></i></a>
                    <a href="https://www.linkedin.com/in/gnavarrog1802" target="_blank"><i class="fa fa-linkedin-square"></i></a>
                    George Navarro
                </p>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/formbs.html
{% extends "base.html" %}
{% block heading %}
    <script>
        $(function() {
            {% block javascript %}
            {% endblock %}

            $("form").validationEngine({autoHidePrompt:true, autoHideDelay:1000 });

            envioformulario = function(){
                var valid = $("form").validationEngine('validate');
                if (valid){
                    $('.datepicker').css({"display": "none"});
                    $('.bootstrap-timepicker-widget').css({"display": "none"});
                    $('.controls input').each(function(){
                        if ($(this).attr('type')=='text'){
                            $(this).val($(this).val().trim());
                        }
                        if ($(this).attr('type')!='file'){
                            if ($(this).css('text-transform')=='uppercase'){
                                if ($(this).attr('type')!='password'){
                                    $(this).val($(this).val().toUpperCase());
                                }
                            }
                        }
                    });
                    var formdata = new FormData($("#formulario")[0]);
                    $.ajax({
                        type: "POST",
                        url: "{% block formaction %}/{% endblock %}",
                        data: formdata,
                        success: function(data) {
                            if (data.result == 'ok') {
                                location.href = "{% block formdestination %}/{% endblock %}" + ((data.id)?data.id:"");
                            }
                            else if (data.result == 'bad_list'){
                                location.href = data.destino;
                            }
                            else {
                                $.unblockUI();
                                smoke.alert(data.mensaje);
                            }
                        },
                        error: function() {
                            $.unblockUI();
                            smoke.alert("Error al enviar los datos.");
                        },
                        dataType: "json",
                        cache: false,
                        contentType: false,
                        processData: false
                    });
                } else {
                    setTimeout(function() {
                        $('.help-text').html("");
                    }, 3500);
                }
            };

            $("#formbutton").click(function(){
                envioformulario();
            });

        });
    </script>
    {% block extraheading %}
    {% endblock %}
{% endblock %}

{% block content %}
    <div class='row spaceupbig'>
        <div class='col-md-12'>
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <i class="glyphicon glyphicon-pencil pull-right"></i>
                            <h4>{% block form_title %}{% endblock %}</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <form id="formulario" class='form-horizontal' enctype="multipart/form-data" autocomplete="off">
                            {% block formextra %}
                            {% endblock %}
                            {% for field in form %}
                                <div class="form-group">
                                    <label for="id_{{ field.name }}" class="col-sm-3 control-label">{{ field.label }}</label>
                                    <div class="col-sm-9">
                                        {{ field }}
                                        <p class="help-text">{{ field.help_text }} </p>
                                    </div>
                                </div>
                            {% endfor %}
                            {% block formsuffix %}
                            {% endblock %}
                            <p style="text-align: right;">
                                <a class="btn btn-success btn-form" id="formbutton"><i class="fa fa-save"></i> {% block buttonname %}Save{% endblock %}</a>
                                <a href="{% block formback %}/{% endblock %}" class="btn btn-default btn-form"><i class="fa fa-arrow-left"></i> Cancel</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-10 col-md-10 text-center">
            <div class="page-header">
                <h2>{{ title }}</h2>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <img src="/static/img/powerball.png"/>
        </div>
    </div>

    <div class="row spaceuphalf">
        <div class="col-lg-6 col-md-6">
            <h3>
                <i class="fa fa-user"></i> PLAYERS
            </h3>

            <table class="table table-responsive table-hover">
                <thead>
                <tr class="bigger">
                    <th>Player</th>
                    <th style="width: 10%; text-align: center">N1</th>
                    <th style="width: 10%; text-align: center">N2</th>
                    <th style="width: 10%; text-align: center">N3</th>
                    <th style="width: 10%; text-align: center">N4</th>
                    <th style="width: 10%; text-align: center">N5</th>
                    <th style="width: 10%; text-align: center">POWB</th>
                </tr>
                </thead>
                <tbody>
                {% for p in players %}
                    <tr class="bigger">
                        <td>{{ p }}</td>
                        <td class="text-center">{{ p.n1|floatformat:0 }}</td>
                        <td class="text-center">{{ p.n2|floatformat:0 }}</td>
                        <td class="text-center">{{ p.n3|floatformat:0 }}</td>
                        <td class="text-center">{{ p.n4|floatformat:0 }}</td>
                        <td class="text-center">{{ p.n5|floatformat:0 }}</td>
                        <td class="text-center">{{ p.powb|floatformat:0 }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="10" class="alert alert-danger">
                            <strong>INSERT PLAYERS</strong> to start testing the application
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="row">
                <a href="/clean_data" class="btn btn-info btn-form tt" title="Delete all players to create new data" style="float: right; margin-left: 1em"><i class="fa fa-refresh"></i> Clean Data</a>
                <a href="/add_player" class="btn btn-success btn-form tt" title="Create new player" style="float: right"><i class="fa fa-plus"></i> Add Player</a>
            </div>
        </div>

        <div class="col-lg-6 col-md-6 text-center">
            <h3><i class="fa fa-money"></i> WINNING NUMBER</h3>
            <div class="text-center">
                <ul id="circles">
                    {% for n in favorite_numbers %}
                        <li>
                            <div class="circle tt" title="Number {{ n }}">
                                <div>{{ n|floatformat:0 }}</div>
                            </div>
                        </li>
                    {% endfor %}
                    <li>
                        <div class="circle_red tt" title="Powerball">
                            <div>{{ powerball_number|floatformat:0 }}</div>
                        </div>
                    </li>
                </ul>
            </div>

        </div>
    </div>
{% endblock %}

templates/players/add.html
{% extends "formbs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            $("#id_firstname, #id_lastname, #id_n1, #id_n2, #id_n3, #id_n4, #id_n5, #id_powb").addClass("validate[required]");

            $("#id_n1, #id_n2, #id_n3, #id_n4, #id_n5").blur(function(){
                numerico($(this), 1, 69, 0);
            });

            $("#id_powb").blur(function(){
                numerico($(this), 1, 26, 0);
            });

        });
    </script>
{% endblock %}
{% block form_title %}{{ title }}{% endblock %}
{% block formaction %}/add_player{% endblock %}
{% block formdestination %}/{% endblock %}
{% block formback %}/{% endblock %}
{% block buttonname %}Create{% endblock %}